FROM node:22-alpine
WORKDIR /app
# Enable pnpm via Corepack
RUN corepack enable
#Copy only manifests first for better caching
COPY package.json pnpm-lock.yaml ./
# Install all dependencies (including dev)
RUN pnpm install --frozen-lockfile
# Copy source code
COPY . .
# Expose the port the app runs in
EXPOSE 8257
# Start the app in development mode
CMD ["pnpm", "start:dev"]